#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t altair"

$L "           _   _______       _____ _____   "
$L "     /\   | | |__   __|/\   |_   _|  __ \  "
$L "    /  \  | |    | |  /  \    | | | |__) | "
$L "   / /\ \ | |    | | / /\ \   | | |  _  /  "
$L "  / ____ \| |____| |/ ____ \ _| |_| | \ \  "
$L " /_/    \_\______|_/_/    \_\_____|_|  \_\ "
$L " "
$L "Welcome to Android `getprop ro.build.version.release` / Altair-`getprop ro.altair.version`";
