PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/altair_ace.mk \
    $(LOCAL_DIR)/altair_anzu.mk \
    $(LOCAL_DIR)/altair_blade.mk \
    $(LOCAL_DIR)/altair_bravo.mk \
    $(LOCAL_DIR)/altair_bravoc.mk \
    $(LOCAL_DIR)/altair_buzz.mk \
    $(LOCAL_DIR)/altair_captivatemtd.mk \
    $(LOCAL_DIR)/altair_click.mk \
    $(LOCAL_DIR)/altair_coconut.mk \
    $(LOCAL_DIR)/altair_cooper.mk \
    $(LOCAL_DIR)/altair_crespo.mk \
    $(LOCAL_DIR)/altair_crespo4g.mk \
    $(LOCAL_DIR)/altair_desirec.mk \
    $(LOCAL_DIR)/altair_dream_sapphire.mk \
    $(LOCAL_DIR)/altair_droid2.mk \
    $(LOCAL_DIR)/altair_droid2we.mk \
    $(LOCAL_DIR)/altair_encore.mk \
    $(LOCAL_DIR)/altair_epicmtd.mk \
    $(LOCAL_DIR)/altair_espresso.mk \
    $(LOCAL_DIR)/altair_es209ra.mk \
    $(LOCAL_DIR)/altair_fascinatemtd.mk \
    $(LOCAL_DIR)/altair_hallon.mk \
    $(LOCAL_DIR)/altair_hero.mk \
    $(LOCAL_DIR)/altair_heroc.mk \
    $(LOCAL_DIR)/altair_inc.mk \
    $(LOCAL_DIR)/altair_iyokan.mk \
    $(LOCAL_DIR)/altair_jordan.mk \
    $(LOCAL_DIR)/altair_jordan_plus.mk \
    $(LOCAL_DIR)/altair_galaxy5.mk \
    $(LOCAL_DIR)/altair_galaxys2.mk \
    $(LOCAL_DIR)/altair_galaxys2att.mk \
    $(LOCAL_DIR)/altair_galaxysbmtd.mk \
    $(LOCAL_DIR)/altair_galaxysmtd.mk \
    $(LOCAL_DIR)/altair_generic.mk \
    $(LOCAL_DIR)/altair_glacier.mk \
    $(LOCAL_DIR)/altair_legend.mk \
    $(LOCAL_DIR)/altair_leo.mk \
    $(LOCAL_DIR)/altair_liberty.mk \
    $(LOCAL_DIR)/altair_mango.mk \
    $(LOCAL_DIR)/altair_mecha.mk \
    $(LOCAL_DIR)/altair_mesmerizemtd.mk \
    $(LOCAL_DIR)/altair_mimmi.mk \
    $(LOCAL_DIR)/altair_morrison.mk \
    $(LOCAL_DIR)/altair_motus.mk \
    $(LOCAL_DIR)/altair_one.mk \
    $(LOCAL_DIR)/altair_olympus.mk \
    $(LOCAL_DIR)/altair_p970.mk \
    $(LOCAL_DIR)/altair_p990.mk \
    $(LOCAL_DIR)/altair_p999.mk \
    $(LOCAL_DIR)/altair_passion.mk \
    $(LOCAL_DIR)/altair_robyn.mk \
    $(LOCAL_DIR)/altair_saga.mk \
    $(LOCAL_DIR)/altair_satsuma.mk \
    $(LOCAL_DIR)/altair_shadow.mk \
    $(LOCAL_DIR)/altair_shakira.mk \
    $(LOCAL_DIR)/altair_sholes.mk \
    $(LOCAL_DIR)/altair_showcasemtd.mk \
    $(LOCAL_DIR)/altair_skate.mk \
    $(LOCAL_DIR)/altair_smb_a1002.mk \
    $(LOCAL_DIR)/altair_smb_a1004.mk \
    $(LOCAL_DIR)/altair_smb_a1011.mk \
    $(LOCAL_DIR)/altair_smb_b9701.mk \
    $(LOCAL_DIR)/altair_smultron.mk \
    $(LOCAL_DIR)/altair_speedy.mk \
    $(LOCAL_DIR)/altair_sunfire.mk \
    $(LOCAL_DIR)/altair_supersonic.mk \
    $(LOCAL_DIR)/altair_tass.mk \
    $(LOCAL_DIR)/altair_u8150.mk \
    $(LOCAL_DIR)/altair_u8160.mk \
    $(LOCAL_DIR)/altair_u8220.mk \
    $(LOCAL_DIR)/altair_urushi.mk \
    $(LOCAL_DIR)/altair_v9.mk \
    $(LOCAL_DIR)/altair_vega.mk \
    $(LOCAL_DIR)/altair_vibrantmtd.mk \
    $(LOCAL_DIR)/altair_vision.mk \
    $(LOCAL_DIR)/altair_vivo.mk \
    $(LOCAL_DIR)/altair_vivow.mk \
    $(LOCAL_DIR)/altair_z71.mk \
    $(LOCAL_DIR)/altair_zeppelin.mk \
    $(LOCAL_DIR)/altair_zero.mk \
    $(LOCAL_DIR)/altair_zeus.mk \
    $(LOCAL_DIR)/altair_zeusc.mk
