#PRODUCT_VERSION_MAJOR = 7
#PRODUCT_VERSION_MINOR = 2
#PRODUCT_VERSION_MAINTENANCE = 0

## Our eng-builds get build_desc, force a user-like build_id
PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID=$(BUILD_ID)

# Set BUILDTYPE

ifdef ALTAIR_NIGHTLY
    ALTAIR_BUILDTYPE := NIGHTLY
endif
ifdef ALTAIR_EXPERIMENTAL
    ALTAIR_BUILDTYPE := EXPERIMENTAL
endif
ifdef ALTAIR_RELEASE
    ALTAIR_BUILDTYPE := RELEASE
endif

ifdef ALTAIR_BUILDTYPE
    ifdef ALTAIR_EXTRAVERSION
        # Force build type to EXPERIMENTAL
        ALTAIR_BUILDTYPE := EXPERIMENTAL
        # Add leading dash to ALTAIR_EXTRAVERSION
        ALTAIR_EXTRAVERSION := -$(ALTAIR_EXTRAVERSION)
    endif
else
    # If ALTAIR_BUILDTYPE is not defined, set to UNOFFICIAL
    ALTAIR_BUILDTYPE := UNOFFICIAL
    ALTAIR_EXTRAVERSION :=
endif

#PRODUCT_FULL_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)-$(ALTAIR_BUILDTYPE)-$(shell date +%Y%m%d-%H%M)
PRODUCT_FULL_VERSION := $(PLATFORM_VERSION)-$(ALTAIR_BUILDTYPE)-$(shell date +%Y%m%d-%H%M)
ALTAIR_VERSION := Altair-$(PRODUCT_FULL_VERSION)-$(ALTAIR_BUILD)

#ifdef ALTAIR_RELEASE
#    ALTAIRVERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)$(PRODUCT_VERSION_DEVICE_SPECIFIC)-$(ALTAIR_BUILD)
#else
#    ALTAIRVERSION := $(PRODUCT_VERSION_MAJOR)-$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)$(PRODUCT_VERSION_DEVICE_SPECIFIC)-$(shell date -u +%Y%m%d)-$(ALTAIR_BUILDTYPE)-$(ALTAIR_BUILD)$(ALTAIR_EXTRAVERSION)
#endif

PRODUCT_PROPERTY_OVERRIDES += \
    ro.modversion=$(ALTAIR_VERSION)
